version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.checko.entrypoints=https"
      - "traefik.http.routers.checko.rule=Host(`checko.dev1.trex-studio.host`)"
      - "traefik.http.routers.checko.tls=true"
      - "traefik.http.routers.checko.tls.certresolver=letsEncrypt"


networks:
  web:
    external: true
